#' Detect trends and quantify their effect on the probability of monthly based SPEI values
#'
#' @param PPE.at.TS
#' A 3-column matrix generated as generated by `PPESaggreg_month()`. No other objects are accepted.
#'  * 1st column is years (YYYY),
#'  * 2nd is the months (1 to 12),
#'  * and 3rd is the difference between P and PE accumulated at a monthly based time scale.
#' @param nonstat.models
#' A single integer number indicating the number of increasingly complex candidate
#' nonstationary models to be considered in the drought assessments (from 1 to 3).
#' If 1, only stationary and nonstationary (linear) in location models are fitted (2 candidates).
#' If 2, a nonstationary (linear) in scale model is included (3 candidates).
#' If 3, a nonstationary (linear) in both location and scale models is included (4 candidates).
#' Default is 3.
#' @param criterion
#' A character string value (`AICc` or `BIC`) defining the selection model criterion.
#' Second-order Akaike Information criterion (`AICc`) or Bayesian information criterion (`BIC`).
#' Default is `AICc`.
#' @returns
#' A `list` object with:
#' \describe{
#'   \item{data.month}{The P - PE amounts, SPEI, cumulative probability of the SPEI values under the stationary
#'   approach, cumulative probability of the SPEI values under the non-stationary approach,
#'   and the changes in the frequency of below zero SPEI values caused by the changes in P - PE patterns.}
#'   \item{Changes.Freq.Drought}{The non-stationary  GEV-based model that best fits the P - PE series,
#'    the expected P - PE amounts describing normal conditions under both stationary and non-stationary
#'    approaches, and the changes in the frequency of moderate to extreme, severe to extreme and extreme drought events}
#'    \item{GEV.parameters}{Parameters of the best fitting GEV model (location, scale and shape) for each quasi-week.}
#'  }
#' @examples
#' set.seed(1)
#' PPE.at.month <- PPEaggreg_month(
#'   Campinas_monthly[,7],
#'   start.year = 1890,
#'   start.month = 1,
#'   TS = 3
#' )
#' Changes_SPEI <- SPEIChanges_month(PPE.at.TS=PPE.at.month,
#'                                  nonstat.models = 3)
#'
#' @importFrom extRemes pevd qevd
#' @importFrom ismev gev.fit
#' @importFrom progress progress_bar
#' @importFrom spsUtil quiet
#' @importFrom stats qnorm
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @importFrom rlang arg_match
#' @export
#'
SPEIChanges_month <- function(PPE.at.TS, nonstat.models = 1, criterion = "AICc"){
  if (!inherits(PPE.at.TS, c("TSaggreg_month", "matrix", "array"))) {
    stop("`PPE.at.TS` must be a matrix that is generated by using `TSaggreg_month()`.")
  }

  if (length(nonstat.models) != 1 || !is.numeric(nonstat.models) ||
      !(nonstat.models %in% 1:3)) {
    stop("`nonstat.models` must be a single integer value between 1 and 3.")
  }

  if (!is.numeric(PPE.at.TS) || anyNA(PPE.at.TS) ||
      ncol(PPE.at.TS) != 3 ) {
    stop("Physically impossible or missing values in PPE.at.TS.")}

  n <- nrow(PPE.at.TS)

  if (n < 120) {
    stop("Less than 10 years of monthly P-PE records. We cannot proceed.")
  }
  if (n < 360) {
    warning("Less than 30 years of P-PE records. Longer periods are highly recommended.")
  }

  if (length(PPE.at.TS[PPE.at.TS[, 2] < 1]) != 0 ||
      length(PPE.at.TS[PPE.at.TS[, 2] > 12]) != 0 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 1]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 2]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 3]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 4]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 5]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 6]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 7]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 8]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 9]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 10]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 11]) < 24 ||
      length(PPE.at.TS[PPE.at.TS[, 2] == 12]) < 24) {
    stop("Column Month in PPE.at.TS is probably malformed.")
  }

  # Print message and ensure newline so progress bar appears on the next line
  message("Fitting the GEV-based models to each monthly-based series...")
  show_pb <- interactive()
  pb <- progress::progress_bar$new(
    format = "  [:bar] :percent | month :current/:total | eta: :eta",
    total = 12,
    clear = FALSE,
    width = 60
  )

  years <- PPE.at.TS[,1]
  months <- PPE.at.TS[,2]
  data.month <- data.frame(matrix(NA, n, 7))
  GEV.parameters <- data.frame(matrix(NA, n, 4))
  data.month[,1:3] <- PPE.at.TS
  data.month <- data.month[order(data.month[,2]),]
  GEV.parameters[,1] <- data.month[,2]
  Changes.Freq.Drought <- matrix(NA,12,7)

  for (month in 1:12) {
    pb$tick()
    PPE.month <- (data.month[which(data.month[, 2] == month), 3])
    sample.size <- length(PPE.month)
    quasiprob.ns <- matrix(NA,sample.size,1)
    if (month > 1) {
      initial.row <- last.row + 1
      last.row <- initial.row + sample.size - 1
    } else{
      initial.row <- 1
      last.row <- sample.size
    }
    time <- as.matrix(seq(1:sample.size))
    time <- (time - min(time)) / (max(time) - min(time))
    t.gev <- quiet(tryCatch(gev.fit(PPE.month, ydat = as.matrix(time), mul = NULL, sigl = NULL, shl = NULL,
                                    mulink = identity, siglink = identity, shlink = identity,
                                    muinit = NULL, siginit = NULL, shinit = NULL, show = TRUE,
                                    method = "Nelder-Mead", maxit = 10000),
                            error = function(e) NULL
    ))
    models <- quiet(Fit.Models(PPE.month, time, nonstat.models, sample.size, criterion = criterion))
    Changes.Freq.Drought[month, 2] <- models$best
    selected.model <- models$selected.model
    quasiprob <- (
      pevd(PPE.month, loc = t.gev$mle[1],
           scale = t.gev$mle[2],
           shape = t.gev$mle[3],
           type = c("GEV"), lower.tail = TRUE, log.p = FALSE)
    )
    quasiprob[quasiprob < 0.001351] <- 0.001351
    quasiprob[quasiprob > 0.998649] <- 0.998649
    data.month[initial.row:last.row, 5] <- quasiprob

    stat.PPE.exp <- qevd(c(0.5,0.159,0.067,0.023), loc = t.gev$mle[1],
                         scale = t.gev$mle[2],
                         shape = t.gev$mle[3],
                         type = c("GEV"), lower.tail = TRUE)
    Changes.Freq.Drought[month, 1] <- month
    #Changes.Freq.Drought[month, 2] <- week
    if (Changes.Freq.Drought[month, 2]==1){
      quasiprob.ns <- quasiprob
      Changes.Freq.Drought[month, 3] <- round(stat.PPE.exp[1],2)
      Changes.Freq.Drought[month, 4] <- Changes.Freq.Drought[month, 3]
      Changes.Freq.Drought[month, 5:7] <- 0
    } else {
      for (i in 1:sample.size){
        quasiprob.ns[i] <- pevd(PPE.month[i], loc = models$loc[i],
                                scale = models$scale[i],
                                shape = models$shape[i],
                                type = c("GEV"), lower.tail = TRUE, log.p = FALSE)}
      Changes.Freq.Drought[month, 3] <- round(stat.PPE.exp[1],2)
      Changes.Freq.Drought [month,4] <- round(qevd(0.5, loc = models$loc[sample.size],
                                                   scale = models$scale[sample.size],
                                                   shape = models$shape[sample.size],
                                                   type = c("GEV"), lower.tail = TRUE),2)
      actual.nsprob <- pevd(stat.PPE.exp, loc = models$loc[sample.size], scale = models$scale[sample.size], shape = models$shape[sample.size],
                            type = c("GEV"), lower.tail = TRUE, log.p = FALSE)
      Changes.Freq.Drought [month,5] <- round(100 *(actual.nsprob[2]-0.159),2)

      Changes.Freq.Drought [month,6] <- round(100 *(actual.nsprob[3]-0.067),2)

      Changes.Freq.Drought [month,7] <- round(100 *(actual.nsprob[4]-0.023),2)
    }

    quasiprob.ns[quasiprob.ns < 0.001351] <- 0.001351
    quasiprob.ns[quasiprob.ns > 0.998649] <- 0.998649
    data.month[initial.row:last.row,6] <- quasiprob.ns

    GEV.parameters[initial.row:last.row, 2] <- models$loc
    GEV.parameters[initial.row:last.row, 3] <- models$scale
    GEV.parameters[initial.row:last.row, 4] <- models$shape
  }

  #close(pb)
  data.month[,4] <- c(qnorm(data.month[,5], mean = 0, sd = 1))
  dry.values <- which(data.month[,6] <= 0)
  wet.values <- which(data.month[,6] > 0)
  data.month[dry.values,7] <- 100*round(data.month[dry.values,6]-data.month[dry.values,5],3)
  data.month[wet.values,7] <- "NoDrought"
  data.month <- data.month[order(data.month[,1]),]
  colnames(data.month) <- c(
    "Year",
    "Month",
    "PPE.at.TS",
    "SPEI",
    "Exp.Acum.Prob",
    "Actual.Acum.Prob",
    "ChangeDryFreq"
  )
  data.month[,3:6] <- round(data.month[,4:6],3)
  colnames(Changes.Freq.Drought) <- c(
    "Month",
    "Model",
    "StatNormalPPE",
    "NonStatNormalPPE",
    "ChangeMod",
    "ChangeSev",
    "ChangeExt"
  )
  colnames(GEV.parameters) <- c(
    "Month",
    "Location","Scale","Shape")

  Drought_Changes <- list(
    data.month = data.month,
    Changes.Freq.Drought = Changes.Freq.Drought,
    GEV.parameters = GEV.parameters
  )
  return(Drought_Changes)
}
